// pcData.js

// data with name, type, description, img path
const photoData = [
    { name: "yushi", type: "album", description: "songbird letter ver.", image: "yushi-album-songbird-letter.avif" },
    { name: "yushi", type: "album", description: "songbird member ver.", image: "yushi-album-songbird-member.avif" },
    { name: "yushi", type: "album", description: "songbird member ver.", image: "yushi-album-songbird-member-2.avif" },
    { name: "yushi", type: "album", description: "songbird member ver.", image: "yushi-album-songbird-member-3.avif" },
    { name: "yushi", type: "album", description: "steady finding psyche ver.", image: "yushi-album-steady-finding-psyche.avif" },
    { name: "yushi", type: "benefit", description: "poppop applemusic lucky draw", image: "yushi-benefit-poppop-applemusic-lucky-draw.avif" },
    { name: "yushi", type: "benefit", description: "poppop jump up", image: "yushi-benefit-poppop-jump-up.avif" },
    { name: "yushi", type: "benefit", description: "songbird countdown live event tmon", image: "yushi-benefit-songbird-countdown-live-event-tmon.avif" },
    { name: "yushi", type: "benefit", description: "songbird dear my muse", image: "yushi-benefit-songbird-dear-my-muse.avif" },
    { name: "yushi", type: "benefit", description: "songbird kms", image: "yushi-benefit-songbird-kms.avif" },
    { name: "yushi", type: "benefit", description: "songbird kms", image: "yushi-benefit-songbird-kms-2.avif" },
    { name: "yushi", type: "benefit", description: "songbird ktown4u", image: "yushi-benefit-songbird-ktown4u.avif" },
    { name: "yushi", type: "benefit", description: "songbird sm store", image: "yushi-benefit-songbird-sm-store.avif" },
    { name: "yushi", type: "benefit", description: "songbird sound wave", image: "yushi-benefit-songbird-sound-wave.avif" },
    { name: "yushi", type: "benefit", description: "songbird withmuu", image: "yushi-benefit-songbird-withmuu.avif" },
    { name: "yushi", type: "benefit", description: "songbird yizhiyu", image: "yushi-benefit-songbird-yizhiyu.avif" },
    { name: "yushi", type: "benefit", description: "steady applemusic", image: "yushi-benefit-steady-applemusic.avif" },
    { name: "yushi", type: "benefit", description: "steady applemusic", image: "yushi-benefit-steady-applemusic-2.avif" },
    { name: "yushi", type: "benefit", description: "steady applemusic", image: "yushi-benefit-steady-applemusic-3.avif" },
    { name: "yushi", type: "benefit", description: "steady beatroad", image: "yushi-benefit-steady-beatroad.avif" },
    { name: "yushi", type: "benefit", description: "steady beatroad lucky draw", image: "yushi-benefit-steady-beatroad-lucky-draw.avif" },
    { name: "yushi", type: "benefit", description: "steady kakao talk", image: "yushi-benefit-steady-kakao-talk.avif" },
    { name: "yushi", type: "benefit", description: "steady kms", image: "yushi-benefit-steady-kms.avif" },
    { name: "yushi", type: "benefit", description: "steady kms", image: "yushi-benefit-steady-kms-2.avif" },
    { name: "yushi", type: "benefit", description: "steady kms lucky draw", image: "yushi-benefit-steady-kms-lucky-draw.avif" },
    { name: "yushi", type: "benefit", description: "steady withmuu", image: "yushi-benefit-steady-withmuu.avif" },
    { name: "yushi", type: "benefit", description: "steady withmuu lucky draw", image: "yushi-benefit-steady-withmuu-lucky-draw.avif" },
    { name: "yushi", type: "benefit", description: "steady ypbooks", image: "yushi-benefit-steady-ypbooks.avif" },
    { name: "yushi", type: "benefit", description: "wishful makestar", image: "yushi-benefit-wishful-makestar.avif" },
    { name: "yushi", type: "benefit", description: "wishful mu-mo shop", image: "yushi-benefit-wishful-mu-mo-shop.avif" },
    { name: "yushi", type: "benefit", description: "wishful sm store", image: "yushi-benefit-wishful-sm-store.avif" },
    { name: "yushi", type: "benefit", description: "wish knpops", image: "yushi-benefit-wish-knpops.avif" },
    { name: "yushi", type: "benefit", description: "wish yizhiyu", image: "yushi-benefit-wish-yizhiyu.avif" },
    { name: "yushi", type: "collabo", description: "dicon volume n°29 a type", image: "yushi-collabo-dicon-volume-no29-a-type.avif" },
    { name: "yushi", type: "collabo", description: "dicon volume n°29 b type", image: "yushi-collabo-dicon-volume-no29-b-type.avif" },
    { name: "yushi", type: "concert", description: "smtown live 2025 tokyo reward", image: "yushi-concert-smtown-live-2025-tokyo-reward.avif" },
    { name: "yushi", type: "etc", description: "1st anniversary seongsu reward", image: "yushi-etc-1st-anni-seongsu-reward.avif" },
    { name: "yushi", type: "etc", description: "[one summer wish] cross bag", image: "yushi-etc-one-summer-wish-cross-bag.avif" },
    { name: "yushi", type: "md", description: "1st anniversary turntable bluetooth speaker", image: "yushi-md-1st-anni-turntable-bluetooth-speaker.avif" },
    { name: "yushi", type: "md", description: "cushion set", image: "yushi-md-cushion-set.avif" },
    { name: "yushi", type: "md", description: "let's go steady reward", image: "yushi-md-lets-go-steady-reward.avif" },
    { name: "riku", type: "album", description: "steady finding psyche ver.", image: "riku-album-steady-finding-psyche.avif" },
    { name: "riku", type: "album", description: "steady i ❤︎ wish ver.", image: "riku-album-steady-i-love-wish.avif" },
    { name: "riku", type: "album", description: "steady qr ver.", image: "riku-album-steady-qr.avif" },
    { name: "riku", type: "album", description: "wishful paper file ver.", image: "riku-album-wishful-all-member-solo.avif" },
    { name: "riku", type: "benefit", description: "poppop applemusic", image: "riku-benefit-poppop-applemusic.avif" },
    { name: "riku", type: "benefit", description: "poppop applemusic lucky draw", image: "riku-benefit-poppop-applemusic-lucky-draw.avif" },
    { name: "riku", type: "benefit", description: "poppop ime", image: "riku-benefit-poppop-ime.avif" },
    { name: "riku", type: "benefit", description: "songbird yizhiyu", image: "riku-benefit-songbird-yizhiyu.avif" },
    { name: "riku", type: "benefit", description: "songbird yizhiyu", image: "riku-benefit-songbird-yizhiyu-2.avif" },
    { name: "riku", type: "benefit", description: "steady applemusic", image: "riku-benefit-steady-applemusic.avif" },
    { name: "riku", type: "benefit", description: "steady beatroad lucky draw", image: "riku-benefit-steady-beatroad-lucky-draw.avif" },
    { name: "riku", type: "benefit", description: "steady everline", image: "riku-benefit-steady-everline.avif" },
    { name: "riku", type: "benefit", description: "steady keyring ver. kms", image: "riku-benefit-steady-keyring-ver-kms.avif" },
    { name: "riku", type: "benefit", description: "steady kms", image: "riku-benefit-steady-kms.avif" },
    { name: "riku", type: "benefit", description: "steady kms", image: "riku-benefit-steady-kms-2.avif" },
    { name: "riku", type: "benefit", description: "steady kms", image: "riku-benefit-steady-kms-3.avif" },
    { name: "riku", type: "benefit", description: "steady withmuu lucky draw", image: "riku-benefit-steady-withmuu-lucky-draw.avif" },
    { name: "riku", type: "benefit", description: "wish knpops", image: "riku-benefit-wish-knpops.avif" },
    { name: "riku", type: "benefit", description: "wish music korea", image: "riku-benefit-wish-music-korea.avif" },
    { name: "riku", type: "collabo", description: "dicon volume n°29 a type", image: "riku-collabo-dicon-volume-no29-a-type.avif" },
    { name: "riku", type: "collabo", description: "dicon volume n°29 b type", image: "riku-collabo-dicon-volume-no29-b-type.avif" },
    { name: "riku", type: "etc", description: "coupon card office worker", image: "riku-etc-coupon-card-office-worker.avif" },
    { name: "riku", type: "etc", description: "[one summer wish] wings keyring", image: "riku-etc-one-summer-wish-wings-keyring.avif" },
    { name: "riku", type: "md", description: "deco sticker set", image: "riku-md-deco-sticker-set.avif" },
    { name: "riku", type: "md", description: "find your color hoodie", image: "riku-md-find-your-color-hoodie.avif" },
    { name: "riku", type: "md", description: "let's go steady reward", image: "riku-md-lets-go-steady-reward.avif" },







];